"""unique username

Revision ID: 8ff617707891
Revises: a4b82f904d2d
Create Date: 2026-03-24 19:01:17.622586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff617707891'
down_revision: Union[str, Sequence[str], None] = 'a4b82f904d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    return None
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    return None
    # ### end Alembic commands ###
